### ISSUE TITLE
error report in python version

### ISSUE THREAD

**Issue by rsy6318** [zhangxy0517/3D-Registration-with-Maximal-Cliques#31]
Hi, I found that in some pairs of source and target point clouds, there exists an error.
Looking forward to your reply!
`(pugeo) siyuren_21@ss420f:~/data1/siyuren_21/3D-Registration-with-Maximal-Cliques-main$ /home/siyuren_21/anaconda3/envs/pugeo/bin/python /home/siyuren_21/data1/siyuren_21/3D-Registration-with-Maximal-Cliques-main/main_rmc_1.py
Graph construction: 12.66ms
Search maximal cliques: 1973.51ms
Total: 41546
After filtered: 4838
Traceback (most recent call last):
  File "/home/siyuren_21/data1/siyuren_21/3D-Registration-with-Maximal-Cliques-main/main_rmc_1.py", line 344, in <module>
    pred_trans,pred_trans1,spend_time=test(src_path,tgt_path)
  File "/home/siyuren_21/data1/siyuren_21/3D-Registration-with-Maximal-Cliques-main/main_rmc_1.py", line 283, in test
    batch_A = src_pts[list(macs[group[i][0]])][None]
IndexError: list index out of range`

**Comment by rsy6318** [comment]
Here is the error reported.

![image](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/26300755/265ea9e4-6e07-4e4b-ac30-93d7e682029a)

**Comment by rsy6318** [comment]
Here is the point clouds I have used, which is produced by voxel downsample from 3DMatch dataset.
[src_tgt_trans.zip](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/files/12640224/src_tgt_trans.zip)

**Comment by zhangxy0517** [comment]
Please also provide the input correspondence data.

**Comment by rsy6318** [comment]
There is no input correspondence data. I use Open3d to calculate FPFH features and then estimate initial correspondence. Here is my test code, which is modified from example_fpfh_fcgf.py.
[main_rmc_1.zip](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/files/12640313/main_rmc_1.zip)

**Comment by zhangxy0517** [comment]
Reason: all the correspondences do not meet the second order compatibility, the values in SCG are all zeros.
![截图 2023-09-16 18-34-20](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/42647472/137f7d18-9965-4580-8c47-011af389cc4b)
If you plan to use downsampled sparse point cloud (5000 points) to calculate FPFH features, ``downsample`` should be set to a much bigger value (e.g. 0.25) to ensure FPFH can compute features for the sparse points correctly.

**Comment by zhangxy0517** [comment]
The bug is fixed, please download the newest code.

**Comment by rsy6318** [comment]
Thanks ! I would like to try it !

**Comment by rsy6318** [comment]
I have run the fixed python code on 3DMatch dataset and get the results "RE: 2.26 TE: 7.14cm", which is different from the results on the paper. Is it normal? Or could you provide your registration results?

**Comment by rsy6318** [comment]
Here is my impliment details. First, we downsample the original point clouds wich voxel size 0.05 and store them. When testing, we calculate the FPFH features and run your fixed codes to get the registration results.
